### PR TITLE
Last features

### PR DESCRIPTION
**Pull request by sebastianlujan**
Hello team we finished the changes, opening pull request for code review

### CODE REVIEW

**Comment by samgaco** [comment]
#### Hi @sebastianlujan and @Usagib :hand: 

#### Following up the review were it was left off https://github.com/sebastianlujan/positioning-and-floating-elements/pull/2 

**This points were previously required and have yet to be met:**

1. >  ### Implement your footer to have a fixed position (it sticks to the bottom part of the screen).

This requirement it is referring to the following:

> footer3-41

As you see in the very bottom of the page, you have a fixed footer (fixed as you did with the current navigation bar)

2. > ### Use semantic html, for a consistent look on your html code.
3. > ### Always endeavor to include these tags in your project: nav, main and the footer tags.

You can read about semantic[ HTML elements here ](https://www.w3schools.com/html/html5_semantic_elements.asp). And please consider adding the `<main>` tag for the dominant content of your project. And `<footer>` for the footer. Apart of using `<aside>` , `<article>` and `<section>` tags.


4. You should add the buttons for **login** and **subscribe** at the rightmost part of the navigation bar.

> button

5. **Correct the linters failing checks**

### Please :pray: work on this five :hand: points and submit back for a code review. You can do it! :muscle:

**Comment by Usagib** [comment]
Finished commiting changes, happy coding, team!

**Comment by samgaco** [comment]
#### Hi @sebastianlujan and @Usagib :smile: 

### Everything is perfect now!! You are good to go... Approved :heavy_check_mark: Congratulations :100: 

#### You may merge now to the master branch and submit the project completion form :1st_place_medal:

**Comment by sebastianlujan** [comment]
T

> #### Hi @sebastianlujan and @Usagib 😄
> ### Everything is perfect now!! You are good to go... Approved ✔️ Congratulations 💯
> #### You may merge now to the master branch and submit the project completion form 🥇

### Thank you for your help!! @samgaco 🚀

**Pull request merged**
